/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as PortfolioIndexImport } from './routes/portfolio/index'
import { Route as PortfolioVolunteeringImport } from './routes/portfolio/volunteering'
import { Route as PortfolioSkillsImport } from './routes/portfolio/skills'
import { Route as PortfolioExperienceImport } from './routes/portfolio/experience'
import { Route as PortfolioEducationImport } from './routes/portfolio/education'
import { Route as PortfolioContactImport } from './routes/portfolio/contact'

// Create/Update Routes

const PortfolioIndexRoute = PortfolioIndexImport.update({
  id: '/portfolio/',
  path: '/portfolio/',
  getParentRoute: () => rootRoute,
} as any)

const PortfolioVolunteeringRoute = PortfolioVolunteeringImport.update({
  id: '/portfolio/volunteering',
  path: '/portfolio/volunteering',
  getParentRoute: () => rootRoute,
} as any)

const PortfolioSkillsRoute = PortfolioSkillsImport.update({
  id: '/portfolio/skills',
  path: '/portfolio/skills',
  getParentRoute: () => rootRoute,
} as any)

const PortfolioExperienceRoute = PortfolioExperienceImport.update({
  id: '/portfolio/experience',
  path: '/portfolio/experience',
  getParentRoute: () => rootRoute,
} as any)

const PortfolioEducationRoute = PortfolioEducationImport.update({
  id: '/portfolio/education',
  path: '/portfolio/education',
  getParentRoute: () => rootRoute,
} as any)

const PortfolioContactRoute = PortfolioContactImport.update({
  id: '/portfolio/contact',
  path: '/portfolio/contact',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/portfolio/contact': {
      id: '/portfolio/contact'
      path: '/portfolio/contact'
      fullPath: '/portfolio/contact'
      preLoaderRoute: typeof PortfolioContactImport
      parentRoute: typeof rootRoute
    }
    '/portfolio/education': {
      id: '/portfolio/education'
      path: '/portfolio/education'
      fullPath: '/portfolio/education'
      preLoaderRoute: typeof PortfolioEducationImport
      parentRoute: typeof rootRoute
    }
    '/portfolio/experience': {
      id: '/portfolio/experience'
      path: '/portfolio/experience'
      fullPath: '/portfolio/experience'
      preLoaderRoute: typeof PortfolioExperienceImport
      parentRoute: typeof rootRoute
    }
    '/portfolio/skills': {
      id: '/portfolio/skills'
      path: '/portfolio/skills'
      fullPath: '/portfolio/skills'
      preLoaderRoute: typeof PortfolioSkillsImport
      parentRoute: typeof rootRoute
    }
    '/portfolio/volunteering': {
      id: '/portfolio/volunteering'
      path: '/portfolio/volunteering'
      fullPath: '/portfolio/volunteering'
      preLoaderRoute: typeof PortfolioVolunteeringImport
      parentRoute: typeof rootRoute
    }
    '/portfolio/': {
      id: '/portfolio/'
      path: '/portfolio'
      fullPath: '/portfolio'
      preLoaderRoute: typeof PortfolioIndexImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/portfolio/contact': typeof PortfolioContactRoute
  '/portfolio/education': typeof PortfolioEducationRoute
  '/portfolio/experience': typeof PortfolioExperienceRoute
  '/portfolio/skills': typeof PortfolioSkillsRoute
  '/portfolio/volunteering': typeof PortfolioVolunteeringRoute
  '/portfolio': typeof PortfolioIndexRoute
}

export interface FileRoutesByTo {
  '/portfolio/contact': typeof PortfolioContactRoute
  '/portfolio/education': typeof PortfolioEducationRoute
  '/portfolio/experience': typeof PortfolioExperienceRoute
  '/portfolio/skills': typeof PortfolioSkillsRoute
  '/portfolio/volunteering': typeof PortfolioVolunteeringRoute
  '/portfolio': typeof PortfolioIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/portfolio/contact': typeof PortfolioContactRoute
  '/portfolio/education': typeof PortfolioEducationRoute
  '/portfolio/experience': typeof PortfolioExperienceRoute
  '/portfolio/skills': typeof PortfolioSkillsRoute
  '/portfolio/volunteering': typeof PortfolioVolunteeringRoute
  '/portfolio/': typeof PortfolioIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/portfolio/contact'
    | '/portfolio/education'
    | '/portfolio/experience'
    | '/portfolio/skills'
    | '/portfolio/volunteering'
    | '/portfolio'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/portfolio/contact'
    | '/portfolio/education'
    | '/portfolio/experience'
    | '/portfolio/skills'
    | '/portfolio/volunteering'
    | '/portfolio'
  id:
    | '__root__'
    | '/portfolio/contact'
    | '/portfolio/education'
    | '/portfolio/experience'
    | '/portfolio/skills'
    | '/portfolio/volunteering'
    | '/portfolio/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  PortfolioContactRoute: typeof PortfolioContactRoute
  PortfolioEducationRoute: typeof PortfolioEducationRoute
  PortfolioExperienceRoute: typeof PortfolioExperienceRoute
  PortfolioSkillsRoute: typeof PortfolioSkillsRoute
  PortfolioVolunteeringRoute: typeof PortfolioVolunteeringRoute
  PortfolioIndexRoute: typeof PortfolioIndexRoute
}

const rootRouteChildren: RootRouteChildren = {
  PortfolioContactRoute: PortfolioContactRoute,
  PortfolioEducationRoute: PortfolioEducationRoute,
  PortfolioExperienceRoute: PortfolioExperienceRoute,
  PortfolioSkillsRoute: PortfolioSkillsRoute,
  PortfolioVolunteeringRoute: PortfolioVolunteeringRoute,
  PortfolioIndexRoute: PortfolioIndexRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/portfolio/contact",
        "/portfolio/education",
        "/portfolio/experience",
        "/portfolio/skills",
        "/portfolio/volunteering",
        "/portfolio/"
      ]
    },
    "/portfolio/contact": {
      "filePath": "portfolio/contact.tsx"
    },
    "/portfolio/education": {
      "filePath": "portfolio/education.tsx"
    },
    "/portfolio/experience": {
      "filePath": "portfolio/experience.tsx"
    },
    "/portfolio/skills": {
      "filePath": "portfolio/skills.tsx"
    },
    "/portfolio/volunteering": {
      "filePath": "portfolio/volunteering.tsx"
    },
    "/portfolio/": {
      "filePath": "portfolio/index.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
